/*
These values control branding strings throughout the entire app. If you're forking, please take a few minutes to update them.

"The website" refers to the website itself that you use to load projects and convert them to another form.

"Packaged projects" refers to the files generated by the website. They include a line of text something like:
`Parts of this script are from the ${APP_NAME} <${WEBSITE}>, licensed as follows: ${COPYRIGHT_NOTICE}`
*/

module.exports = {
  // The name of the app. This text is included in packaged projects.
  APP_NAME: 'TurboWarp Packager',

  // A longer form of the app's name. Used by the website.
  LONG_NAME: 'TurboWarp Packager for Scratch',

  // Your app's website. This link is included in packaged projects.
  WEBSITE: 'https://packager.turbowarp.org/',

  // A copyright notice regarding the app. This text is included in packaged projects.
  // Also make sure to update the "License" section in README.md
  COPYRIGHT_NOTICE: `Copyright (C) 2021 Thomas Weber

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License version 3
as published by the Free Software Foundation.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.`,

  // Where users can find the app's source code. This link is included in the website.
  // Note that due to the license used by the project (see README.md), you may be required to make the source code available to all visitors.
  SOURCE_CODE: 'https://github.com/TurboWarp/packager',

  // Feedback/bug report links shown in various places throughout the website.
  // These don't strictly need to be Scratch or GitHub links, but some parts of the interface label them that way.
  FEEDBACK_SCRATCH: 'https://scratch.mit.edu/users/GarboMuffin/#comments',
  FEEDBACK_GITHUB: 'https://github.com/TurboWarp/packager/issues'
};
