<script>
  import Section from './Section.svelte';
  const color = '#b117f8';
</script>

<Section accent={color}>
  <div>
    <p>
      WKWebView macOS applications generated by the packager between May 24, 2022 and June 3, 2022 are broken and must be regenerated.
    </p>
  </div>
</Section>
